version: '3.8'

services:
 api:
  build:
   context: bitcoindca
   dockerfile: Dockerfile
  ports:
   - 5000:5000
   - 9229:9229
  environment:
   - SERVER_PORT=3000
  volumes:
   - ./bitcoindca/:/app
  command: npm run debug

 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  command: --init-file /data/application/init.sql
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - ./init.sql:/data/application/init.sql
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

 client:
  build:
   context: client
   dockerfile: Dockerfile
  ports:
  - 3000:3000
  volumes:
  - './client/:/app'
  command: npm start


volumes:
  mysql:
  mysql_config:
