version: '3.8'

services:
 notes:
  build:
   context: bitcoindca
   dockerfile: Dockerfile
  ports:
   - 3000:3000
   - 9229:9229
  environment:
   - SERVER_PORT=3000
  volumes:
   - ./bitcoindca/:/app
  command: npm run debug


 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
